apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    {{- if eq .Values.deployEnv "staging" }}
    pods: "4"
    services: "4"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "16Gi"
    persistentvolumeclaims: "0"
    {{- end }}
    {{- if eq .Values.deployEnv "canary" }}
    pods: "10"
    limits.cpu: "4"
    limits.memory: "8Gi"
    persistentvolumeclaims: "0"
    {{- end }}
    {{- if eq .Values.deployEnv "production" }}
    pods: "100"
    limits.cpu: "8"
    limits.memory: "16Gi"
    persistentvolumeclaims: "0"
    {{- end }}
